.TH BD_LIST_TITLES "1" "July 2020" "libbluray 1.2.1" "User Commands"
.SH NAME
bd_list_titles \- List the titles and title info of a BD disc
.SH DESCRIPTION
\fI\,bd_list_titles\fP <BD base dir> [\-s <seconds>]
.TP
\fB\-s\fR #    \- Filter out titles shorter than # seconds
.TP
\fB\-a\fR      \- List all titles
.TP
\fB\-l\fR      \- Show language codes
.TP
\fB\-h\fR      \- This message
.SH AUTHOR
This manpage was written by Vasyl Gello.
